import { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { 
  Plus, 
  FileText, 
  Bell, 
  Trash2, 
  Search,
  Filter
} from 'lucide-react';
import { jsPDF } from 'jspdf';
import { collection, addDoc, onSnapshot, query, orderBy, deleteDoc, doc, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase';
import { Student, UserProfile } from '../types';
import { cn } from '../lib/utils';

interface StudentTrackerProps {
  user: UserProfile;
}

export default function StudentTracker({ user }: StudentTrackerProps) {
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  
  // Form state
  const [name, setName] = useState('');
  const [grade, setGrade] = useState('');
  const [score, setScore] = useState('');
  const [attendance, setAttendance] = useState('');
  const [assignments, setAssignments] = useState('');

  useEffect(() => {
    const q = query(collection(db, 'students'), orderBy('createdAt', 'desc'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const studentData = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as Student[];
      setStudents(studentData);
      setLoading(false);
    });
    return () => unsubscribe();
  }, []);

  const computeRisk = (score: number, att: number, assign: number) => {
    const risk = 100 - (score * 0.5 + att * 0.3 + (assign / 10) * 100 * 0.2);
    if (risk > 55) return { label: 'HIGH', color: '#f87171' };
    if (risk > 35) return { label: 'MED', color: '#fbbf24' };
    return { label: 'LOW', color: '#34d399' };
  };

  const handleAddStudent = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !score || !attendance) return;

    const sVal = parseFloat(score);
    const aVal = parseFloat(attendance);
    const asVal = parseFloat(assignments) || 0;
    const risk = computeRisk(sVal, aVal, asVal);

    try {
      await addDoc(collection(db, 'students'), {
        name,
        grade,
        score: sVal,
        attendance: aVal,
        assignments: asVal,
        riskLevel: risk.label,
        addedBy: user.uid,
        createdAt: serverTimestamp()
      });
      
      setName('');
      setGrade('');
      setScore('');
      setAttendance('');
      setAssignments('');
      showToast('Student added successfully! ✅');
    } catch (err) {
      showToast('Error adding student.', 'error');
    }
  };

  const handleDelete = async (id: string) => {
    if (user.role !== 'admin') return;
    try {
      await deleteDoc(doc(db, 'students', id));
      showToast('Student removed.');
    } catch (err) {
      showToast('Error removing student.', 'error');
    }
  };

  const exportPDF = () => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();
    
    doc.setFontSize(22);
    doc.text('EduLens Student Report', 20, 20);
    doc.setFontSize(12);
    doc.text(`Generated on: ${date}`, 20, 30);
    doc.text(`Generated by: ${user.displayName}`, 20, 37);

    let y = 50;
    doc.setFontSize(10);
    doc.text('NAME', 20, y);
    doc.text('GRADE', 60, y);
    doc.text('SCORE', 90, y);
    doc.text('ATTENDANCE', 120, y);
    doc.text('RISK', 160, y);
    
    doc.line(20, y + 2, 190, y + 2);
    y += 10;

    students.forEach(s => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(s.name, 20, y);
      doc.text(s.grade || '-', 60, y);
      doc.text(`${s.score}%`, 90, y);
      doc.text(`${s.attendance}%`, 120, y);
      doc.text(s.riskLevel, 160, y);
      y += 8;
    });

    doc.save(`EduLens_Report_${date}.pdf`);
    showToast('📄 PDF report downloaded!');
  };

  const showToast = (msg: string, type: 'success' | 'error' = 'success') => {
    const container = document.getElementById('toast-container');
    if (!container) return;
    const toast = document.createElement('div');
    toast.className = cn(
      "flex items-center gap-2 rounded-xl border px-4 py-3 text-sm shadow-2xl animate-in slide-in-from-right-full",
      type === 'success' ? "bg-[#0f1a2e] border-[#34d399]/30 text-white" : "bg-[#0f1a2e] border-[#f87171]/30 text-white"
    );
    toast.innerHTML = `${type === 'success' ? '✅' : '⚠'} ${msg}`;
    container.appendChild(toast);
    setTimeout(() => toast.remove(), 3000);
  };

  const filteredStudents = students.filter(s => 
    s.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    s.grade.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="space-y-8"
    >
      <div className="text-center">
        <span className="inline-block rounded-full border border-[#34d399]/30 bg-[#34d399]/10 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-[#34d399]">
          Student Tracker
        </span>
        <h2 className="mt-4 font-syne text-3xl font-extrabold text-white">Manage <span className="text-[#38bdf8]">Students</span></h2>
        <p className="mt-2 font-instrument text-[#64748b]">Add students, track performance, and generate reports.</p>
      </div>

      <div className="rounded-3xl border border-white/10 bg-[#0f1a2e] p-8 shadow-2xl">
        {user.role === 'admin' && (
          <form onSubmit={handleAddStudent} className="mb-8 space-y-6 border-b border-white/5 pb-8">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">
              <div className="space-y-1">
                <label className="text-[10px] font-bold uppercase tracking-wider text-[#64748b]">Name</label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="w-full rounded-xl border border-white/10 bg-[#0b1220] px-4 py-2 text-sm text-white outline-none focus:border-[#38bdf8]"
                  placeholder="Student Name"
                  required
                />
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-bold uppercase tracking-wider text-[#64748b]">Grade</label>
                <input
                  type="text"
                  value={grade}
                  onChange={(e) => setGrade(e.target.value)}
                  className="w-full rounded-xl border border-white/10 bg-[#0b1220] px-4 py-2 text-sm text-white outline-none focus:border-[#38bdf8]"
                  placeholder="e.g. 10A"
                />
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-bold uppercase tracking-wider text-[#64748b]">Score %</label>
                <input
                  type="number"
                  value={score}
                  onChange={(e) => setScore(e.target.value)}
                  className="w-full rounded-xl border border-white/10 bg-[#0b1220] px-4 py-2 text-sm text-white outline-none focus:border-[#38bdf8]"
                  placeholder="0-100"
                  required
                />
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-bold uppercase tracking-wider text-[#64748b]">Attendance %</label>
                <input
                  type="number"
                  value={attendance}
                  onChange={(e) => setAttendance(e.target.value)}
                  className="w-full rounded-xl border border-white/10 bg-[#0b1220] px-4 py-2 text-sm text-white outline-none focus:border-[#38bdf8]"
                  placeholder="0-100"
                  required
                />
              </div>
              <div className="flex items-end">
                <button
                  type="submit"
                  className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#34d399] py-2 font-syne text-sm font-bold text-[#050a12] transition-all hover:bg-[#6ee7b7]"
                >
                  <Plus size={18} />
                  Add Student
                </button>
              </div>
            </div>
          </form>
        )}

        <div className="mb-6 flex flex-wrap items-center justify-between gap-4">
          <div className="relative flex-1 min-w-[240px]">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#64748b]" size={18} />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search students or grades..."
              className="w-full rounded-xl border border-white/10 bg-[#0b1220] py-2 pl-10 pr-4 text-sm text-white outline-none focus:border-[#38bdf8]"
            />
          </div>
          <div className="flex gap-2">
            <button
              onClick={exportPDF}
              className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold text-[#38bdf8] transition-all hover:bg-white/10"
            >
              <FileText size={18} />
              Export PDF
            </button>
            <button
              className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold text-[#f87171] transition-all hover:bg-white/10"
            >
              <Bell size={18} />
              Risk Alerts
            </button>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full border-collapse text-left">
            <thead>
              <tr className="border-b border-white/5 text-[10px] font-bold uppercase tracking-wider text-[#64748b]">
                <th className="px-4 py-3">Name</th>
                <th className="px-4 py-3">Grade</th>
                <th className="px-4 py-3">Score</th>
                <th className="px-4 py-3">Attendance</th>
                <th className="px-4 py-3">Risk Level</th>
                {user.role === 'admin' && <th className="px-4 py-3 text-right">Actions</th>}
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {loading ? (
                <tr>
                  <td colSpan={6} className="py-8 text-center text-[#64748b]">Loading students...</td>
                </tr>
              ) : filteredStudents.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-8 text-center text-[#64748b]">No students found.</td>
                </tr>
              ) : (
                filteredStudents.map((s) => (
                  <tr key={s.id} className="group transition-all hover:bg-white/5">
                    <td className="px-4 py-4 font-syne text-sm font-bold text-white">{s.name}</td>
                    <td className="px-4 py-4 text-sm text-[#64748b]">{s.grade || '-'}</td>
                    <td className="px-4 py-4 text-sm text-white">{s.score}%</td>
                    <td className="px-4 py-4 text-sm text-white">{s.attendance}%</td>
                    <td className="px-4 py-4">
                      <div className="flex items-center gap-3">
                        <div className="h-1.5 w-24 overflow-hidden rounded-full bg-white/5">
                          <div 
                            className={cn(
                              "h-full transition-all duration-500",
                              s.riskLevel === 'HIGH' ? "bg-[#f87171]" :
                              s.riskLevel === 'MED' ? "bg-[#fbbf24]" :
                              "bg-[#34d399]"
                            )}
                            style={{ width: `${s.riskLevel === 'HIGH' ? 80 : s.riskLevel === 'MED' ? 50 : 20}%` }}
                          />
                        </div>
                        <span className={cn(
                          "rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider",
                          s.riskLevel === 'HIGH' ? "bg-[#f87171]/10 text-[#f87171]" :
                          s.riskLevel === 'MED' ? "bg-[#fbbf24]/10 text-[#fbbf24]" :
                          "bg-[#34d399]/10 text-[#34d399]"
                        )}>
                          {s.riskLevel}
                        </span>
                      </div>
                    </td>
                    {user.role === 'admin' && (
                      <td className="px-4 py-4 text-right">
                        <button
                          onClick={() => s.id && handleDelete(s.id)}
                          className="rounded-lg p-2 text-[#64748b] transition-all hover:bg-[#f87171]/10 hover:text-[#f87171]"
                        >
                          <Trash2 size={16} />
                        </button>
                      </td>
                    )}
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </motion.div>
  );
}
